# Generated by Django 2.2 on 2020-04-07 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200407_0908'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogComment',
            new_name='PostComment',
        ),
    ]
