# Generated by Django 2.2 on 2020-03-30 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_purchaser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_order_item', to='features.Feature'),
        ),
    ]
