# Generated by Django 2.2 on 2020-03-23 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_auto_20200323_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='votes',
        ),
        migrations.DeleteModel(
            name='FeatureVote',
        ),
    ]
