# Generated by Django 2.2 on 2020-03-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_auto_20200323_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='purchases',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1000),
        ),
    ]
