# Generated by Django 2.2 on 2020-03-30 15:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('features', '0004_feature_purchases'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='contributors',
            field=models.ManyToManyField(related_name='feature_contributors', to=settings.AUTH_USER_MODEL),
        ),
    ]
