# Generated by Django 2.2 on 2020-04-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0007_auto_20200330_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='when_implemented',
            field=models.DateTimeField(null=True),
        ),
    ]
