# Generated by Django 2.2 on 2020-04-05 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0008_feature_when_implemented'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='features_reported', to=settings.AUTH_USER_MODEL),
        ),
    ]
