# Generated by Django 2.2 on 2020-04-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0009_auto_20200405_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='when_implemented',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
