# Generated by Django 2.2 on 2020-04-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0010_auto_20200409_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='category',
            field=models.CharField(blank=True, choices=[('User-Requested', 'User-Requested'), ('Roadmap', 'Roadmap')], default='User-Requested', max_length=16),
        ),
        migrations.AlterField(
            model_name='feature',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Funded', 'Funded'), ('Implementing', 'Implementing'), ('Testing', 'Testing'), ('Implemented', 'Implemented')], default='Requested', max_length=12),
        ),
    ]
