# Generated by Django 2.2 on 2020-03-09 21:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='severity',
            field=models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='LOW', max_length=10),
        ),
        migrations.AddField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ACTIVE', 'Active'), ('TESTING', 'Testing'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=10),
        ),
        migrations.AlterField(
            model_name='bug',
            name='user_votes',
            field=models.ManyToManyField(default=1, related_name='bugs_voted', to=settings.AUTH_USER_MODEL),
        ),
    ]
