# Generated by Django 2.2 on 2020-03-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_auto_20200309_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='slug',
        ),
        migrations.AlterField(
            model_name='bug',
            name='severity',
            field=models.CharField(default='LOW', max_length=10),
        ),
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(default='OPEN', max_length=10),
        ),
    ]
