# Generated by Django 2.2 on 2020-04-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_auto_20200322_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='when_resolved',
            field=models.DateTimeField(null=True),
        ),
    ]
