# Generated by Django 2.2 on 2020-03-12 20:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0003_auto_20200310_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='user_votes',
            field=models.ManyToManyField(related_name='bugs_voted', to=settings.AUTH_USER_MODEL),
        ),
    ]
