# Generated by Django 2.2 on 2020-04-05 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0004_bug_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bugs_reported', to=settings.AUTH_USER_MODEL),
        ),
    ]
