# Generated by Django 2.2 on 2020-03-13 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0005_bugcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bugcomment',
            old_name='name',
            new_name='author',
        ),
    ]
