# Generated by Django 2.2 on 2020-03-13 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0006_auto_20200313_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bugcomment',
            old_name='body',
            new_name='comment',
        ),
    ]
