# Generated by Django 2.2 on 2020-03-14 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugs', '0007_auto_20200313_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bugcomment',
            options={'ordering': ('-created',)},
        ),
        migrations.RemoveField(
            model_name='bug',
            name='user_votes',
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugs.Bug')),
                ('bug_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugs.BugComment')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bug',
            name='votes',
            field=models.ManyToManyField(related_name='bug_votes', through='bugs.Vote', to=settings.AUTH_USER_MODEL),
        ),
    ]
