# Generated by Django 2.2 on 2020-03-16 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0008_auto_20200314_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='bug_comment',
        ),
    ]
