# Generated by Django 2.2 on 2020-03-18 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0010_auto_20200318_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='comment',
            new_name='bug_comment',
        ),
    ]
