# Generated by Django 2.2 on 2020-03-18 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0011_auto_20200318_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugcomment',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='bug_comment',
        ),
    ]
