# Generated by Django 2.2 on 2020-03-18 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugs', '0012_auto_20200318_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugs.BugComment')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bugcomment',
            name='votes',
            field=models.ManyToManyField(related_name='comment_votes', through='bugs.VoteComment', to=settings.AUTH_USER_MODEL),
        ),
    ]
