# Generated by Django 2.2 on 2020-03-19 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0013_auto_20200318_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugcomment',
            name='votes',
        ),
        migrations.DeleteModel(
            name='VoteComment',
        ),
    ]
